notifications:
  commits:      commits@juneau.apache.org
  issues:       dev@juneau.apache.org
  pullrequests: dev@juneau.apache.org
  jira_options: link label worklog
  jobs:         dev@juneau.apache.org
  discussions:  dev@juneau.apache.org

# Configure staging website (safe testing)
staging:
  profile: ~
  whoami: asf-staging
  
github:
  description: "Apache Juneau"
  homepage: https://juneau.apache.org/
  labels:
    # Top 20 most important topics for discoverability
    - java
    - serialization
    - rest-api
    - microservices
    - json
    - xml
    - spring-boot
    - jetty
    - configuration
    - testing
    - mocking
    - data-binding
    - swagger
    - openapi
    - pojo
    - zero-dependency
    - lightweight
    - performance
    - juneau
    - apache
  features:
    wiki: true
    issues: true
    projects: true
    discussions: true
