notifications:
  commits:      commits@juneau.apache.org
  issues:       dev@juneau.apache.org
  pullrequests: dev@juneau.apache.org
  jira_options: link label worklog
  jobs:         dev@juneau.apache.org
  discussions:  dev@juneau.apache.org

# Configure staging website (safe testing)
staging:
  profile: ~
  whoami: asf-staging
  
github:
  description: "Apache Juneau"
  homepage: https://juneau.apache.org/
  labels:
    # Core technology
    - java
    - serialization
    - rest-api
    - microservices
    - json
    - xml
    - http-client
    - servlet
    # Framework integration
    - spring-boot
    - jetty
    - jax-rs
    - maven
    - osgi
    # Use cases
    - configuration
    - testing
    - mocking
    - data-binding
    - content-negotiation
    - swagger
    - openapi
    # Technical features
    - pojo
    - bean
    - fluent-api
    - zero-dependency
    - lightweight
    - performance
    # Format support
    - json5
    - html
    - url-encoding
    - messagepack
    - rdf
    - csv
    - soap
    # Project specific
    - juneau
    - apache
    - website
    - docusaurus
  features:
    wiki: true
    issues: true
    projects: true
    discussions: true
