notifications:
  commits:      commits@juneau.apache.org
  issues:       dev@juneau.apache.org
  pullrequests: dev@juneau.apache.org
  jira_options: link label worklog
  jobs:         dev@juneau.apache.org
  discussions:  dev@juneau.apache.org

# Configure staging website (safe testing)
staging:
  profile: ~
  whoami: asf-staging
  
github:
  description: "Apache Juneau"
  homepage: https://juneau.apache.org/
  labels:
    - json
    - juneau
    - http
    - rest
    - apache
    - website
    - docusaurus
  features:
    wiki: true
    issues: true
    projects: true
    discussions: true
  del_branch_on_merge: true   # Delete head branches after merge
  merge_commit: true          # Allow merge commits
  rebase_merge: true          # Allow rebase merging